Repository gdscwce/Bollywood-songs-for-you, pull requests merged in 2021-10, with the labels that each got.

#51 Update index.json
  index.json
Labels: hacktoberfest-accepted

#59 Update index.json
  index.json
Labels: hacktoberfest-accepted

#58 added 50
  index.json
Labels: hacktoberfest-accepted

#63 Update index.json
  index.json
Labels: hacktoberfest-accepted

#66 Update index.json
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#67 Update index.json
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#69 Update index.json
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#70 Update index.json (added new song)
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#71 Updated index.json
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#72 Update index.json
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#73 Update index.json
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#74 Update index.json
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#75 Tu Tu Hai Wahi
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#76 I have added the song from line no 685 to 692
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#77 Added a song data
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#78 I have added a song from line 680 to 687.
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#79 Update index.json
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#83 I have added a song from line 728 to735.
  index.json
Labels: Hacktoberfest

#85 Update index.json
  index.json
Labels: Hacktoberfest

#86 Update index.json
  index.json
Labels: Hacktoberfest

#88 Update index.json
  index.json
Labels: Hacktoberfest

#89 I have added a song from line no 648 to 655
  index.json
Labels: hacktoberfest-accepted

#92 Updated Index.json
  index.json
Labels: hacktoberfest-accepted

#91 Update index.json
  index.json
Labels: hacktoberfest-accepted

#90 Update index.json
  index.json
Labels: hacktoberfest-accepted

#99 Update index.json
  index.json
Labels: hacktoberfest-accepted

#98 Update index.json
  index.json
Labels: hacktoberfest-accepted

#97 Update index.json and added more data
  index.json
Labels: hacktoberfest-accepted

#96 Update index.json
  index.json
Labels: hacktoberfest-accepted

#95 Added Songs
  index.json
Labels: hacktoberfest-accepted

#104 Update index.json
  index.json
Labels: hacktoberfest-accepted

#103 81 to 85
  index.json
Labels: hacktoberfest-accepted

#101 Updated index.json file
  index.json
Labels: hacktoberfest-accepted

#100 fix: Missed semicolons and formatting
  index.json
Labels: hacktoberfest-accepted
